insert into ifest.produto (nm_produto, ds_produto, vl_produto, nr_endereco, id_endereco, id_categoria) values ('Vestido de noiva', 'Vestido de noiva', 100, 123, 1, 1);
insert into ifest.produto (nm_produto, ds_produto, vl_produto, nr_endereco, id_endereco, id_categoria) values ('Traje do noivo', 'Traje do noivo', 100, 789, 2, 2);
insert into ifest.produto (nm_produto, ds_produto, vl_produto, nr_endereco, id_endereco, id_categoria) values ('Convites', 'Convites', 750, 789, 3, 3);
insert into ifest.produto (nm_produto, ds_produto, vl_produto, nr_endereco, id_endereco, id_categoria) values ('Decoração', 'Decoração', 1000, 1213, 4, 4);
insert into ifest.produto (nm_produto, ds_produto, vl_produto, nr_endereco, id_endereco, id_categoria) values ('Bolo de casamento', 'Bolo de casamento', 100, 1011, 5, 5);
insert into ifest.produto (nm_produto, ds_produto, vl_produto, nr_endereco, id_endereco, id_categoria) values ('Doces finos', 'Doces finos', 900, 1213, 6, 6);
insert into ifest.produto (nm_produto, ds_produto, vl_produto, nr_endereco, id_endereco, id_categoria) values ('Buffet', 'Buffet', 500, 1213, 7, 7);
insert into ifest.produto (nm_produto, ds_produto, vl_produto, nr_endereco, id_endereco, id_categoria) values ('Bebidas', 'Bebidas', 1000, 1213, 8, 8);
insert into ifest.produto (nm_produto, ds_produto, vl_produto, nr_endereco, id_endereco, id_categoria) values ('Música', 'Música', 100, 456, 9, 9);
insert into ifest.produto (nm_produto, ds_produto, vl_produto, nr_endereco, id_endereco, id_categoria) values ('Fotografia', 'Fotografia', 100, 456, 10, 10);
insert into ifest.produto (nm_produto, ds_produto, vl_produto, nr_endereco, id_endereco, id_categoria) values ('Filmagem', 'Filmagem', 1000, 1213, 11, 11);
insert into ifest.produto (nm_produto, ds_produto, vl_produto, nr_endereco, id_endereco, id_categoria) values ('Lembrancinhas', 'Lembrancinhas', 750, 789, 12, 12);
insert into ifest.produto (nm_produto, ds_produto, vl_produto, nr_endereco, id_endereco, id_categoria) values ('Alianças', 'Alianças', 900, 1213, 13, 13);
insert into ifest.produto (nm_produto, ds_produto, vl_produto, nr_endereco, id_endereco, id_categoria) values ('Buquê da noiva', 'Buquê da noiva', 750, 456, 14, 14);
insert into ifest.produto (nm_produto, ds_produto, vl_produto, nr_endereco, id_endereco, id_categoria) values ('Sapatos da noiva', 'Sapatos da noiva', 900, 1011, 15, 15);
insert into ifest.produto (nm_produto, ds_produto, vl_produto, nr_endereco, id_endereco, id_categoria) values ('Sapatos do noivo', 'Sapatos do noivo', 750, 123, 16, 16);
insert into ifest.produto (nm_produto, ds_produto, vl_produto, nr_endereco, id_endereco, id_categoria) values ('Cabelo e maquiagem', 'Cabelo e maquiagem', 1000, 1213, 17, 17);
insert into ifest.produto (nm_produto, ds_produto, vl_produto, nr_endereco, id_endereco, id_categoria) values ('Transporte', 'Transporte', 500, 1213, 18, 18);
insert into ifest.produto (nm_produto, ds_produto, vl_produto, nr_endereco, id_endereco, id_categoria) values ('Local da cerimônia', 'Local da cerimônia', 900, 123, 19, 19);
insert into ifest.produto (nm_produto, ds_produto, vl_produto, nr_endereco, id_endereco, id_categoria) values ('Local da festa', 'Local da festa', 500, 1213, 20, 20);
insert into ifest.produto (nm_produto, ds_produto, vl_produto, nr_endereco, id_endereco, id_categoria) values ('Iluminação', 'Iluminação', 750, 456, 21, 21);
insert into ifest.produto (nm_produto, ds_produto, vl_produto, nr_endereco, id_endereco, id_categoria) values ('Gerador de energia', 'Gerador de energia', 500, 789, 22, 22);
insert into ifest.produto (nm_produto, ds_produto, vl_produto, nr_endereco, id_endereco, id_categoria) values ('Segurança', 'Segurança', 1000, 1213, 23, 23);
insert into ifest.produto (nm_produto, ds_produto, vl_produto, nr_endereco, id_endereco, id_categoria) values ('Assessoria de casamento', 'Assessoria de casamento', 500, 1213, 24, 24);
insert into ifest.produto (nm_produto, ds_produto, vl_produto, nr_endereco, id_endereco, id_categoria) values ('Lista de presentes', 'Lista de presentes', 100, 1011, 25, 25);
insert into ifest.produto (nm_produto, ds_produto, vl_produto, nr_endereco, id_endereco, id_categoria) values ('Lua de mel', 'Lua de mel', 1000, 1011, 26, 26);
insert into ifest.produto (nm_produto, ds_produto, vl_produto, nr_endereco, id_endereco, id_categoria) values ('Cerimonialista', 'Cerimonialista', 750, 1011, 27, 27);
insert into ifest.produto (nm_produto, ds_produto, vl_produto, nr_endereco, id_endereco, id_categoria) values ('Aluguel de mobiliário', 'Aluguel de mobiliário', 900, 1213, 28, 28);
insert into ifest.produto (nm_produto, ds_produto, vl_produto, nr_endereco, id_endereco, id_categoria) values ('Aluguel de louças', 'Aluguel de louças', 900, 456, 29, 29);
insert into ifest.produto (nm_produto, ds_produto, vl_produto, nr_endereco, id_endereco, id_categoria) values ('Aluguel de toalhas', 'Aluguel de toalhas', 750, 1213, 30, 30);
insert into ifest.produto (nm_produto, ds_produto, vl_produto, nr_endereco, id_endereco, id_categoria) values ('Aluguel de talheres', 'Aluguel de talheres', 900, 1213, 31, 31);
insert into ifest.produto (nm_produto, ds_produto, vl_produto, nr_endereco, id_endereco, id_categoria) values ('Aluguel de copos', 'Aluguel de copos', 750, 456, 32, 32);
insert into ifest.produto (nm_produto, ds_produto, vl_produto, nr_endereco, id_endereco, id_categoria) values ('Aluguel de mesas e cadeiras', 'Aluguel de mesas e cadeiras', 750, 123, 33, 33);
insert into ifest.produto (nm_produto, ds_produto, vl_produto, nr_endereco, id_endereco, id_categoria) values ('Aluguel de tendas', 'Aluguel de tendas', 900, 123, 34, 34);
insert into ifest.produto (nm_produto, ds_produto, vl_produto, nr_endereco, id_endereco, id_categoria) values ('Aluguel de climatizadores', 'Aluguel de climatizadores', 900, 1011, 35, 35);
insert into ifest.produto (nm_produto, ds_produto, vl_produto, nr_endereco, id_endereco, id_categoria) values ('Aluguel de geradores', 'Aluguel de geradores', 500, 1213, 36, 36);
insert into ifest.produto (nm_produto, ds_produto, vl_produto, nr_endereco, id_endereco, id_categoria) values ('Aluguel de som e iluminação', 'Aluguel de som e iluminação', 900, 1213, 37, 37);
insert into ifest.produto (nm_produto, ds_produto, vl_produto, nr_endereco, id_endereco, id_categoria) values ('Aluguel de pista de dança', 'Aluguel de pista de dança', 100, 123, 38, 38);
insert into ifest.produto (nm_produto, ds_produto, vl_produto, nr_endereco, id_endereco, id_categoria) values ('Aluguel de telão', 'Aluguel de telão', 1000, 789, 39, 39);
insert into ifest.produto (nm_produto, ds_produto, vl_produto, nr_endereco, id_endereco, id_categoria) values ('Aluguel de projetor', 'Aluguel de projetor', 500, 1011, 40, 40);
insert into ifest.produto (nm_produto, ds_produto, vl_produto, nr_endereco, id_endereco, id_categoria) values ('Aluguel de microfones', 'Aluguel de microfones', 500, 456, 41, 41);
insert into ifest.produto (nm_produto, ds_produto, vl_produto, nr_endereco, id_endereco, id_categoria) values ('Aluguel de instrumentos musicais', 'Aluguel de instrumentos musicais', 750, 123, 42, 42);
insert into ifest.produto (nm_produto, ds_produto, vl_produto, nr_endereco, id_endereco, id_categoria) values ('Aluguel de carro antigo', 'Aluguel de carro antigo', 900, 456, 43, 43);
insert into ifest.produto (nm_produto, ds_produto, vl_produto, nr_endereco, id_endereco, id_categoria) values ('Aluguel de carruagem', 'Aluguel de carruagem', 1000, 1011, 44, 44);
insert into ifest.produto (nm_produto, ds_produto, vl_produto, nr_endereco, id_endereco, id_categoria) values ('Aluguel de helicóptero', 'Aluguel de helicóptero', 500, 1011, 45, 45);
insert into ifest.produto (nm_produto, ds_produto, vl_produto, nr_endereco, id_endereco, id_categoria) values ('Aluguel de barco', 'Aluguel de barco', 500, 456, 46, 46);
insert into ifest.produto (nm_produto, ds_produto, vl_produto, nr_endereco, id_endereco, id_categoria) values ('Aluguel de cavalo', 'Aluguel de cavalo', 900, 456, 47, 47);
insert into ifest.produto (nm_produto, ds_produto, vl_produto, nr_endereco, id_endereco, id_categoria) values ('Aluguel de carrinho de pipoca', 'Aluguel de carrinho de pipoca', 1000, 456, 48, 48);
insert into ifest.produto (nm_produto, ds_produto, vl_produto, nr_endereco, id_endereco, id_categoria) values ('Aluguel de carrinho de algodão doce', 'Aluguel de carrinho de algodão doce', 1000, 1011, 49, 49);
insert into ifest.produto (nm_produto, ds_produto, vl_produto, nr_endereco, id_endereco, id_categoria) values ('Aluguel de carrinho de cachorro-quente', 'Aluguel de carrinho de cachorro-quente', 100, 1213, 50, 50);
